// src/lib/navbar.svelte
<div class="drawer h-20">
  <input id="my-drawer-3" type="checkbox" class="drawer-toggle"> 
  <div class="flex flex-col drawer-content">
    <div class="w-full navbar bg-blue-500">
      <div class="flex-none lg:hidden">
        <label for="my-drawer-3" class="btn btn-square btn-ghost">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-6 h-6 stroke-current">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </label>
      </div> 
      <div class="flex-1 px-2 mx-2 py-2">
        <span class="text-lg text-bold pr-2">
              Spectera
        </span>
        <sub class="text-sm text-semibold">
          Another Advanced Bot
        </sub>
      </div> 
      <div class="flex-none hidden lg:block">
        <ul class="menu horizontal">
          <li>
            <a class="rounded-btn" href="https://www.guide.spectera-bot.tk">Guide</a>
          </li> 
          <li>
            <a class="rounded-btn" href="invalid-uri">Config</a>
          </li>
        </ul>
      </div>
    </div>
  </div> 
  <div class="drawer-side">
    <label for="my-drawer-3" class="drawer-overlay"></label> 
    <ul class="p-4 overflow-y-auto menu w-80 bg-base-100">
      <li>
        <a href="https://guide.spectera-bot.tk">Guide</a>
      </li> 
      <li>
        <a href="invalid-uri">Config</a>
      </li>
    </ul>
  </div>
</div>

// src/components/Navbar.vue
<template>
<div class="drawer h-20">
  <input id="my-drawer-3" type="checkbox" class="drawer-toggle"> 
  <div class="flex flex-col drawer-content">
    <div class="w-full navbar bg-blue-500">
      <div class="flex-none lg:hidden">
        <label for="my-drawer-3" class="btn btn-square btn-ghost">
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" class="inline-block w-6 h-6 stroke-current">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16"></path>
          </svg>
        </label>
      </div> 
      <div class="flex-1 px-2 mx-2 py-2">
        <span class="text-lg text-bold pr-2">
              Spectera
        </span>
        <sub class="text-sm text-semibold">
          Another Advanced Bot
        </sub>
      </div> 
      <div class="flex-none hidden lg:block">
        <ul class="menu horizontal">
          <li>
            <a class="rounded-btn">Guide</a>
          </li> 
          <li>
            <a class="rounded-btn">Config</a>
          </li>
        </ul>
      </div>
    </div>
  </div> 
  <div class="drawer-side">
    <label for="my-drawer-3" class="drawer-overlay"></label> 
    <ul class="p-4 overflow-y-auto menu w-80 bg-base-100">
      <li>
        <a>Guide</a>
      </li> 
      <li>
        <a>Config</a>
      </li>
    </ul>
  </div>
</div>
</template>
